pub mod error;
pub mod globals;
pub mod r#type;
pub mod value;

use std::{cell::RefCell, collections::BTreeMap, rc::Rc};

use num_enum::TryFromPrimitive;

use crate::{
    compiler::{
        Upvalue,
        chunk::{Chunk, Function},
        constants::Constant,
        index::{
            ConstantIndex, FunctionIndex, InstructionPointer, LocalIndex, StackIndex, UpvalueIndex,
        },
        instruction::{Instruction, OpCode},
    },
    interner::Interner,
    source::Spanned,
    vm::{
        error::{Result, RuntimeError},
        globals::Globals,
        r#type::Type,
        value::{Closure, UpvalueCell, Value},
    },
};

/// Whether instruction tracking is enabled or not.
pub const DEBUG_INSTRUCTION_TRACKING: bool = false;

/// Executes bytecode generated by the [`compiler`] in [`Chunk`] format.
pub struct VM {
    /// The mapping of all declared global variables.
    pub(crate) globals: Globals,

    /// The runtime stack of function call frames.
    frames: Vec<CallFrame>,

    /// The runtime stack of values being accumulated.
    stack: Vec<Value>,

    /// A mapping of indices of local variables to any currently open upvalues.
    open_upvalues: BTreeMap<StackIndex, Rc<RefCell<UpvalueCell>>>,
}

/// The context of a function invocation.
struct CallFrame {
    /// The index to the instruction currently being executed, also known as the instruction
    /// pointer.
    ip: InstructionPointer,

    /// The [`Closure`] being called within this frame.
    closure: Rc<Closure>,

    /// The offset from the base of the [`VM::stack`] where the locals for this frame begin.
    slot_base: usize,
}

impl VM {
    /// Creates a new virtual machine, but does not begin program execution.
    pub fn new() -> Self {
        Self {
            globals: Globals::new(),
            frames: Vec::new(),
            stack: Vec::new(),
            open_upvalues: BTreeMap::new(),
        }
    }

    /// Executes the provided [`Function`] (usually a complete program) until program termination.
    pub fn execute(&mut self, function: Rc<Function>) -> Result<Option<Value>> {
        self.stack = Vec::with_capacity(128);
        self.frames = vec![CallFrame {
            ip: InstructionPointer(0),
            slot_base: 0,
            closure: Rc::new(Closure {
                function,
                // the global scope doesn't capture any upvalues
                upvalues: Vec::new(),
            }),
        }];

        loop {
            if DEBUG_INSTRUCTION_TRACKING {
                let ip = self.frame().ip;
                let instruction =
                    Instruction::decode(&self.frame().closure.function.chunk.code, ip).0;

                println!("\n=== instruction dump ===");
                println!("ip:          {ip}");
                println!("instruction: {instruction:?}",);
                println!("stack:       {:?}", self.stack);
                println!("globals:     {:?}", self.globals);
                println!("========================\n");
            }

            let opcode = OpCode::try_from_primitive(self.read_byte()).unwrap();

            match opcode {
                OpCode::Return => {
                    let result = self.stack.pop();
                    let frame = self.pop_frame();

                    self.close_above(StackIndex(frame.slot_base as u16));
                    self.stack.truncate(frame.slot_base);

                    if self.frames.len() == 0 {
                        return Ok(result);
                    }

                    self.stack.push(result.unwrap_or(Value::Unit));
                }

                OpCode::Duplicate => {
                    let top = self.stack.last().unwrap().clone();
                    self.stack.push(top);
                }

                OpCode::Pop => {
                    let _ = self.pop_stack();
                }

                OpCode::PopUnder => {
                    let n = self.read_byte();
                    let top = self.pop_stack();

                    self.stack.truncate(self.stack.len() - n as usize);
                    self.stack.push(top);
                }

                OpCode::CloseAbove => {
                    let base = u16::from_ne_bytes([self.read_byte(), self.read_byte()]);
                    self.close_above(StackIndex(base));
                }

                OpCode::Jump => {
                    let offset = i16::from_ne_bytes([self.read_byte(), self.read_byte()]);
                    let frame = self.frame_mut();
                    frame.ip = frame.ip.offset(offset);
                }

                OpCode::JumpIfTrue => {
                    let offset = i16::from_ne_bytes([self.read_byte(), self.read_byte()]);

                    if self.pop_stack().is_truthy() {
                        let frame = self.frame_mut();
                        frame.ip = frame.ip.offset(offset);
                    }
                }

                OpCode::JumpIfFalse => {
                    let offset = i16::from_ne_bytes([self.read_byte(), self.read_byte()]);

                    if !self.pop_stack().is_truthy() {
                        let frame = self.frame_mut();
                        frame.ip = frame.ip.offset(offset);
                    }
                }

                OpCode::LoadConstant => {
                    let constant = self.load_constant();
                    self.stack.push(Value::from(constant));
                }

                OpCode::MakeClosure => {
                    let function = self.load_function();

                    // resolve all upvalues
                    let mut upvalues = Vec::with_capacity(function.upvalues.len());

                    for upvalue in &function.upvalues {
                        let cell = match upvalue {
                            // compute absolute stack location
                            Upvalue::Local(slot_offset) => {
                                let stack_location = StackIndex(
                                    self.frame().slot_base as u16 + slot_offset.0 as u16,
                                );

                                // dedupelicate prexisting open upvalues
                                if let Some(cell) = self.open_upvalues.get(&stack_location) {
                                    Rc::clone(&cell)
                                } else {
                                    let cell =
                                        Rc::new(RefCell::new(UpvalueCell::Open(stack_location)));

                                    self.open_upvalues.insert(stack_location, Rc::clone(&cell));

                                    cell
                                }
                            }

                            // query for upvalue in parent scope
                            Upvalue::Transitive(UpvalueIndex(index)) => {
                                let parent = &self.frames[self.frames.len() - 1];
                                parent.closure.upvalues[*index as usize].clone()
                            }
                        };

                        upvalues.push(cell);
                    }

                    self.stack
                        .push(Value::Closure(Rc::new(Closure { function, upvalues })));
                }

                OpCode::Call => {
                    let arguments = self.read_byte();
                    let slot_base = self.stack.len() - arguments as usize - 1;

                    let span = self.chunk().span_at(self.frame().ip.previous());

                    let callee = self.stack[slot_base].clone();
                    let Value::Closure(closure) = callee else {
                        return Err(Spanned::new(
                            RuntimeError::NotCallable {
                                callee: Type::from(callee),
                            },
                            span,
                        ));
                    };

                    if closure.function.arity != arguments {
                        return Err(Spanned::new(
                            RuntimeError::MismatchedArity {
                                name: closure
                                    .function
                                    .name
                                    .unwrap_or(Interner::intern("<anonymous>")),
                                expected: closure.function.arity as usize,
                                actual: arguments as usize,
                            },
                            span,
                        ));
                    }

                    self.frames.push(CallFrame {
                        ip: InstructionPointer(0),
                        closure,
                        slot_base,
                    });
                }

                OpCode::DefineGlobal => {
                    let Constant::Symbol(name) = self.load_constant() else {
                        panic!("index into constant pool for global was not a symbol");
                    };

                    let value = self.pop_stack();

                    self.globals.runtime.insert(name, value);
                }

                OpCode::GetGlobal => {
                    let Constant::Symbol(name) = self.load_constant() else {
                        panic!("index into constant pool for global was not a symbol");
                    };

                    let value = self
                        .globals
                        .runtime
                        .get(&name)
                        .expect("unbound global should have been caught by compiler")
                        .clone();

                    self.stack.push(value);
                }

                OpCode::SetGlobal => {
                    let Constant::Symbol(name) = self.load_constant() else {
                        panic!("index into constant pool for global was not a symbol");
                    };

                    let value = self.pop_stack().clone();
                    self.globals.runtime.insert(name, value);
                }

                OpCode::GetUpvalue => {
                    let index = UpvalueIndex(self.read_byte());
                    let upvalue = &self.frame().closure.upvalues[index.0 as usize];

                    let value = match &*upvalue.borrow() {
                        UpvalueCell::Open(StackIndex(index)) => &self.stack[*index as usize],
                        UpvalueCell::Closed(value) => value,
                    }
                    .clone();

                    self.stack.push(value);
                }

                OpCode::SetUpvalue => {
                    let index = UpvalueIndex(self.read_byte());
                    let value = self.pop_stack();

                    let upvalue = self.frame().closure.upvalues[index.0 as usize].clone();

                    match &mut *upvalue.borrow_mut() {
                        UpvalueCell::Open(StackIndex(index)) => self.stack[*index as usize] = value,
                        UpvalueCell::Closed(closed) => *closed = value,
                    }
                }

                OpCode::GetLocal => {
                    let index = LocalIndex(self.read_byte());
                    let base = self.frame().slot_base;
                    let value = self.stack[base + index.0 as usize].clone();
                    self.stack.push(value);
                }

                OpCode::SetLocal => {
                    let index = LocalIndex(self.read_byte());
                    let base = self.frame().slot_base;

                    let value = self.pop_stack();

                    self.stack[base + index.0 as usize] = value;
                }

                OpCode::Print => {
                    let value = self.pop_stack();
                    println!("{value}");
                }

                OpCode::Assert => {
                    let value = self.pop_stack();
                    let span = self.chunk().span_at(self.frame().ip.previous());

                    if !value.is_truthy() {
                        return Err(Spanned::new(RuntimeError::AssertionFailed(value), span));
                    }
                }

                OpCode::Add
                | OpCode::Subtract
                | OpCode::Multiply
                | OpCode::Divide
                | OpCode::Equals
                | OpCode::LessThan
                | OpCode::LessThanEquals => {
                    self.handle_binary_operation(opcode)?;
                }

                OpCode::Negate | OpCode::Not => self.handle_unary_operation(opcode)?,
            }
        }
    }

    /// Closes over all open [`UpvalueCell`]s who stack locations >= `bottom`.
    fn close_above(&mut self, bottom: StackIndex) {
        let captured = self.open_upvalues.split_off(&bottom);

        for (_, upvalue) in captured.into_iter() {
            let index = {
                let UpvalueCell::Open(StackIndex(index)) = &*upvalue.borrow() else {
                    unreachable!("upvalue should not have already been closed")
                };

                *index
            };

            *upvalue.borrow_mut() = UpvalueCell::Closed(self.stack[index as usize].clone());
        }
    }

    /// Handles a non shortcircuiting binary instruction.
    fn handle_binary_operation(&mut self, opcode: OpCode) -> Result<()> {
        let rhs = self.pop_stack();
        let lhs = self.pop_stack();

        let reducer = match opcode {
            OpCode::Add => Value::add,
            OpCode::Subtract => Value::subtract,
            OpCode::Multiply => Value::multiply,
            OpCode::Divide => Value::divide,
            OpCode::Equals => Value::equals,
            OpCode::LessThan => Value::less_than,
            OpCode::LessThanEquals => Value::less_than_equals,
            _ => unreachable!("called handle_binary_operation with non binary opcode"),
        };

        let span = self.chunk().span_at(self.frame().ip.previous());

        self.stack
            .push(reducer(lhs, rhs).map_err(|e| Spanned::new(e, span))?);

        Ok(())
    }

    /// Handles a unary instruction.
    fn handle_unary_operation(&mut self, opcode: OpCode) -> Result<()> {
        let operand = self.pop_stack();

        let reducer = match opcode {
            OpCode::Negate => Value::negate,
            OpCode::Not => Value::not,
            _ => unreachable!("called handle_unary_operation with non unary opcode"),
        };

        let span = self.chunk().span_at(self.frame().ip.previous());

        self.stack
            .push(reducer(operand).map_err(|e| Spanned::new(e, span))?);

        Ok(())
    }

    /// Pops a value from the top of the stack.
    fn pop_stack(&mut self) -> Value {
        self.stack
            .pop()
            .expect("should never encounted a stack underflow")
    }

    /// Pops a frame from the top of the stack.
    fn pop_frame(&mut self) -> CallFrame {
        self.frames
            .pop()
            .expect("should never encounted a stack underflow")
    }

    /// Returns an immutable reference to the current [`CallFrame`].
    fn frame(&self) -> &CallFrame {
        self.frames.last().unwrap()
    }

    /// Returns a mutable reference to the current [`CallFrame`].
    fn frame_mut(&mut self) -> &mut CallFrame {
        self.frames.last_mut().unwrap()
    }

    /// Retuns an immutable reference to the current frame's chunk.
    fn chunk(&self) -> &Chunk {
        &self.frame().closure.function.chunk
    }

    /// Returns the [`Constant`] indexed from the current byte from the current frame's [`Chunk::constants`].
    fn load_constant(&mut self) -> Constant {
        let n = self.read_byte();
        self.chunk().constants[ConstantIndex(n)]
    }

    /// Returns the [`Function`] indexed from the current byte from the current frame's [`Chunk::functions`].
    fn load_function(&mut self) -> Rc<Function> {
        let n = FunctionIndex(self.read_byte());
        Rc::clone(&self.chunk().functions[n.0 as usize])
    }

    /// Reads one byte from the current frame's [`Chunk::code`], advancing the instruction pointer by one byte.
    fn read_byte(&mut self) -> u8 {
        let frame = self.frame_mut();
        let value = frame.closure.function.chunk[frame.ip];
        frame.ip = frame.ip.next();
        value
    }
}
