pub mod error;
pub mod r#type;
pub mod value;

use num_enum::TryFromPrimitive;

use crate::{
    compiler::chunk::{Chunk, OpCode, disassemble_instruction},
    source::Spanned,
    vm::{error::Result, value::Value},
};

/// Whether instruction tracking is enabled or not.
pub const DEBUG_INSTRUCTION_TRACKING: bool = true;

/// Executes bytecode generated by the [`compiler`] in [`Chunk`] format.
pub struct VM {
    /// The [`Chunk`] being ran.
    ///
    /// TODO: make this Rc<Chunk>
    chunk: Chunk,

    /// The index to the instruction currently being executed, also known as the instruction
    /// pointer.
    ip: usize,

    /// The runtime stack of values being accumulated.
    stack: Vec<Value>,
}

impl VM {
    /// Creates a new virtual machine, but does not begin program execution
    pub fn new(chunk: Chunk) -> Self {
        Self {
            chunk,
            ip: 0,
            stack: Vec::with_capacity(128),
        }
    }

    /// Executes the current [`Chunk`] until program termination.
    pub fn execute(mut self) -> Result<Option<Value>> {
        loop {
            if DEBUG_INSTRUCTION_TRACKING {
                println!("\n=== instruction dump ===");
                println!("ip:          {}", self.ip);
                println!(
                    "instruction: {:?}",
                    disassemble_instruction(&self.chunk, self.ip).0
                );
                println!("stack:       {:?}", self.stack);
                println!("========================\n");
            }

            let opcode = OpCode::try_from_primitive(self.read_byte()).unwrap();

            match opcode {
                OpCode::Return => {
                    return Ok(self.stack.pop());
                }

                OpCode::Pop => {
                    let _ = self.pop_stack();
                }

                OpCode::LoadConstant => {
                    let index = self.read_byte() as usize;
                    let constant = self.chunk.constants[index];

                    self.stack.push(Value::from(constant));

                    println!("constant: {constant:?}");
                }

                OpCode::Add | OpCode::Subtract | OpCode::Multiply | OpCode::Divide => {
                    self.handle_binary_operation(opcode)?;
                }

                OpCode::Negate | OpCode::Not => self.handle_unary_operation(opcode)?,
            }
        }
    }

    /// Handles a non shortcircuiting binary instruction.
    fn handle_binary_operation(&mut self, opcode: OpCode) -> Result<()> {
        let rhs = self.pop_stack();
        let lhs = self.pop_stack();

        let reducer = match opcode {
            OpCode::Add => Value::add,
            OpCode::Subtract => Value::subtract,
            OpCode::Multiply => Value::multiply,
            OpCode::Divide => Value::divide,

            _ => unreachable!("called handle_binary_operation with non binary opcode"),
        };

        let span = self.chunk.span_at(self.ip - 1);

        self.stack
            .push(reducer(lhs, rhs).map_err(|e| Spanned::wrap(e, span))?);

        Ok(())
    }

    /// Handles a unary instruction.
    fn handle_unary_operation(&mut self, opcode: OpCode) -> Result<()> {
        let operand = self.pop_stack();

        let reducer = match opcode {
            OpCode::Negate => Value::negate,
            OpCode::Not => Value::not,
            _ => unreachable!("called handle_unary_operation with non unary opcode"),
        };

        let span = self.chunk.span_at(self.ip - 1);

        self.stack
            .push(reducer(operand).map_err(|e| Spanned::wrap(e, span))?);

        Ok(())
    }

    /// Pops a value from the top of the stack.
    fn pop_stack(&mut self) -> Value {
        self.stack
            .pop()
            .expect("should never encounted a stack underflow")
    }

    /// Reads one byte from the [`Chunk::code`], advancing the instruction pointer by one byte.
    fn read_byte(&mut self) -> u8 {
        let value = self.chunk.code[self.ip];
        self.ip += 1;
        value
    }
}
