pub mod error;
pub mod globals;
pub mod r#type;
pub mod value;

use std::rc::Rc;

use num_enum::TryFromPrimitive;

use crate::{
    compiler::{
        chunk::{Chunk, Function},
        constants::Constant,
        instruction::{Instruction, OpCode},
    },
    interner::Interner,
    source::Spanned,
    vm::{
        error::{Result, RuntimeError},
        globals::Globals,
        r#type::Type,
        value::{Closure, Value},
    },
};

/// Whether instruction tracking is enabled or not.
pub const DEBUG_INSTRUCTION_TRACKING: bool = false;

/// Executes bytecode generated by the [`compiler`] in [`Chunk`] format.
pub struct VM {
    /// The mapping of all declared global variables.
    pub(crate) globals: Globals,

    /// The runtime stack of function call frames.
    frames: Vec<CallFrame>,

    /// The runtime stack of values being accumulated.
    stack: Vec<Value>,
}

/// The context of a function invocation.
struct CallFrame {
    /// The index to the instruction currently being executed, also known as the instruction
    /// pointer.
    ip: usize,

    /// The [`Closure`] being called within this frame.
    closure: Rc<Closure>,

    /// The offset from the base of the [`VM::stack`] where the locals for this frame begin.
    slot_base: usize,
}

impl VM {
    /// Creates a new virtual machine, but does not begin program execution.
    pub fn new() -> Self {
        Self {
            globals: Globals::new(),
            stack: Vec::new(),
            frames: Vec::new(),
        }
    }

    /// Executes the provided [`Function`] (usually a complete program) until program termination.
    pub fn execute(&mut self, function: Rc<Function>) -> Result<Option<Value>> {
        self.stack = Vec::with_capacity(128);
        self.frames = vec![CallFrame {
            ip: 0,
            slot_base: 0,
            closure: Rc::new(Closure::from(function)),
        }];

        loop {
            if DEBUG_INSTRUCTION_TRACKING {
                let ip = self.frame().ip;
                let instruction =
                    Instruction::decode(&self.frame().closure.function.chunk.code, ip).0;

                println!("\n=== instruction dump ===");
                println!("ip:          {ip}");
                println!("instruction: {instruction:?}",);
                println!("stack:       {:?}", self.stack);
                println!("globals:     {:?}", self.globals);
                println!("========================\n");
            }

            let opcode = OpCode::try_from_primitive(self.read_byte()).unwrap();

            match opcode {
                OpCode::Return => {
                    let result = self.stack.pop();
                    let frame = self.pop_frame();
                    self.stack.truncate(frame.slot_base);

                    if self.frames.len() == 0 {
                        return Ok(result);
                    }

                    self.stack.push(result.unwrap_or(Value::Unit));
                }

                OpCode::Duplicate => {
                    let top = self.stack.last().unwrap().clone();
                    self.stack.push(top);
                }

                OpCode::Pop => {
                    let _ = self.pop_stack();
                }

                OpCode::PopUnder => {
                    let n = self.read_byte();
                    let top = self.pop_stack();

                    self.stack.truncate(self.stack.len() - n as usize);
                    self.stack.push(top);
                }

                OpCode::Jump => {
                    let offset = i16::from_ne_bytes([self.read_byte(), self.read_byte()]);
                    let frame = self.frame_mut();
                    frame.ip = frame.ip.saturating_add_signed(offset as isize);
                }

                OpCode::JumpIfTrue => {
                    let offset = i16::from_ne_bytes([self.read_byte(), self.read_byte()]);

                    if self.pop_stack().is_truthy() {
                        let frame = self.frame_mut();
                        frame.ip = frame.ip.saturating_add_signed(offset as isize);
                    }
                }

                OpCode::JumpIfFalse => {
                    let offset = i16::from_ne_bytes([self.read_byte(), self.read_byte()]);

                    if !self.pop_stack().is_truthy() {
                        let frame = self.frame_mut();
                        frame.ip = frame.ip.saturating_add_signed(offset as isize);
                    }
                }

                OpCode::LoadConstant => {
                    let constant = self.load_constant();
                    self.stack.push(Value::from(constant));
                }

                OpCode::MakeClosure => {
                    let function = self.load_function();
                    self.stack.push(Value::from(function));
                }

                OpCode::Call => {
                    let arguments = self.read_byte();
                    let slot_base = self.stack.len() - arguments as usize - 1;

                    let span = self.chunk().span_at(self.frame().ip - 1);

                    let callee = self.stack[slot_base].clone();
                    let Value::Closure(closure) = callee else {
                        return Err(Spanned::new(
                            RuntimeError::NotCallable {
                                callee: Type::from(callee),
                            },
                            span,
                        ));
                    };

                    if closure.function.arity != arguments {
                        return Err(Spanned::new(
                            RuntimeError::MismatchedArity {
                                name: closure
                                    .function
                                    .name
                                    .unwrap_or(Interner::intern("<anonymous>")),
                                expected: closure.function.arity as usize,
                                actual: arguments as usize,
                            },
                            span,
                        ));
                    }

                    self.frames.push(CallFrame {
                        ip: 0,
                        closure,
                        slot_base,
                    });
                }

                OpCode::DefineGlobal => {
                    let Constant::Symbol(name) = self.load_constant() else {
                        panic!("index into constant pool for global was not a symbol");
                    };

                    let value = self.pop_stack();

                    self.globals.runtime.insert(name, value);
                }

                OpCode::GetGlobal => {
                    let Constant::Symbol(name) = self.load_constant() else {
                        panic!("index into constant pool for global was not a symbol");
                    };

                    let value = self
                        .globals
                        .runtime
                        .get(&name)
                        .expect("unbound global should have been caught by compiler")
                        .clone();

                    self.stack.push(value);
                }

                OpCode::SetGlobal => {
                    let Constant::Symbol(name) = self.load_constant() else {
                        panic!("index into constant pool for global was not a symbol");
                    };

                    let value = self.pop_stack().clone();
                    self.globals.runtime.insert(name, value);
                }

                OpCode::GetLocal => {
                    let index = self.read_byte() as usize;
                    let base = self.frame().slot_base;
                    let value = self.stack[base + index].clone();
                    self.stack.push(value);
                }

                OpCode::SetLocal => {
                    let index = self.read_byte() as usize;
                    let base = self.frame().slot_base;

                    let value = self.pop_stack();

                    self.stack[index + base] = value;
                }

                OpCode::Print => {
                    let value = self.pop_stack();
                    println!("{value}");
                }

                OpCode::Add
                | OpCode::Subtract
                | OpCode::Multiply
                | OpCode::Divide
                | OpCode::Equals
                | OpCode::LessThan
                | OpCode::LessThanEquals => {
                    self.handle_binary_operation(opcode)?;
                }

                OpCode::Negate | OpCode::Not => self.handle_unary_operation(opcode)?,
            }
        }
    }

    /// Handles a non shortcircuiting binary instruction.
    fn handle_binary_operation(&mut self, opcode: OpCode) -> Result<()> {
        let rhs = self.pop_stack();
        let lhs = self.pop_stack();

        let reducer = match opcode {
            OpCode::Add => Value::add,
            OpCode::Subtract => Value::subtract,
            OpCode::Multiply => Value::multiply,
            OpCode::Divide => Value::divide,
            OpCode::Equals => Value::equals,
            OpCode::LessThan => Value::less_than,
            OpCode::LessThanEquals => Value::less_than_equals,
            _ => unreachable!("called handle_binary_operation with non binary opcode"),
        };

        let span = self.chunk().span_at(self.frame().ip - 1);

        self.stack
            .push(reducer(lhs, rhs).map_err(|e| Spanned::new(e, span))?);

        Ok(())
    }

    /// Handles a unary instruction.
    fn handle_unary_operation(&mut self, opcode: OpCode) -> Result<()> {
        let operand = self.pop_stack();

        let reducer = match opcode {
            OpCode::Negate => Value::negate,
            OpCode::Not => Value::not,
            _ => unreachable!("called handle_unary_operation with non unary opcode"),
        };

        let span = self.chunk().span_at(self.frame().ip - 1);

        self.stack
            .push(reducer(operand).map_err(|e| Spanned::new(e, span))?);

        Ok(())
    }

    /// Pops a value from the top of the stack.
    fn pop_stack(&mut self) -> Value {
        self.stack
            .pop()
            .expect("should never encounted a stack underflow")
    }

    /// Pops a frame from the top of the stack.
    fn pop_frame(&mut self) -> CallFrame {
        self.frames
            .pop()
            .expect("should never encounted a stack underflow")
    }

    /// Returns an immutable reference to the current [`CallFrame`].
    fn frame(&self) -> &CallFrame {
        self.frames.last().unwrap()
    }

    /// Returns a mutable reference to the current [`CallFrame`].
    fn frame_mut(&mut self) -> &mut CallFrame {
        self.frames.last_mut().unwrap()
    }

    /// Retuns an immutable reference to the current frame's chunk.
    fn chunk(&self) -> &Chunk {
        &self.frame().closure.function.chunk
    }

    /// Returns the [`Constant`] indexed from the current byte from the current frame's [`Chunk::constants`].
    fn load_constant(&mut self) -> Constant {
        let n = self.read_byte();
        self.chunk().constants[n]
    }

    /// Returns the [`Function`] indexed from the current byte from the current frame's [`Chunk::functions`].
    fn load_function(&mut self) -> Rc<Function> {
        let n = self.read_byte();
        Rc::clone(&self.chunk().functions[n as usize])
    }

    /// Reads one byte from the current frame's [`Chunk::code`], advancing the instruction pointer by one byte.
    fn read_byte(&mut self) -> u8 {
        let frame = self.frame_mut();
        let value = frame.closure.function.chunk.code[frame.ip];
        frame.ip += 1;
        value
    }
}
